name: nprophet
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - pip
  - pip:
    - pillow==8.3.0
    - matplotlib==3.4.2
    - numpy==1.21.0
    - pandas==1.2.5
    - torch==1.9.0
    - neuralprophet==0.2.7
